# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/shatter_sample_vivado.srcs/sources_1/ip/ila_0_5/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/shatter_sample_vivado.srcs/sources_1/ip/ila_0_5/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ECE_385_Labs/shatter_sample/shatter_sample_vivado_files/fuckeverything.gen/sources_1/ip/ila_0_1/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
